// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'libfirebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBU_Kzo4Dt0DjHQBBYNisfrHJRm-OKgQ',
    appId: '1:360259584274:web:0b0f955a2dc0cfddb533cb',
    messagingSenderId: '360259584274',
    projectId: 'caltrack-4a93c',
    authDomain: 'caltrack-4a93c.firebaseapp.com',
    storageBucket: 'caltrack-4a93c.appspot.com',
    measurementId: 'G-6R9XEWB2LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA15mDvedBG2UgSAKCKEW-HDFX6MG2chHU',
    appId: '1:360259584274:android:a25b955f83a445f0b533cb',
    messagingSenderId: '360259584274',
    projectId: 'caltrack-4a93c',
    storageBucket: 'caltrack-4a93c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVkbUWr6SHZF3IDxrhcSwAkHP1dM_CGI',
    appId: '1:360259584274:ios:d1f55a01b28c13bab533cb',
    messagingSenderId: '360259584274',
    projectId: 'caltrack-4a93c',
    storageBucket: 'caltrack-4a93c.appspot.com',
    iosBundleId: 'com.example.caltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqVkbUWr6SHZF3IDxrhcSwAkHP1dM_CGI',
    appId: '1:360259584274:ios:d1f55a01b28c13bab533cb',
    messagingSenderId: '360259584274',
    projectId: 'caltrack-4a93c',
    storageBucket: 'caltrack-4a93c.appspot.com',
    iosBundleId: 'com.example.caltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBU_Kzo4Dt0DjHQBBYNisfrHJRm-OKgQ',
    appId: '1:360259584274:web:f24ca5c0bb8e2852b533cb',
    messagingSenderId: '360259584274',
    projectId: 'caltrack-4a93c',
    authDomain: 'caltrack-4a93c.firebaseapp.com',
    storageBucket: 'caltrack-4a93c.appspot.com',
    measurementId: 'G-XRWTDLNGXT',
  );

}